<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookingSystem.Application\BookingSystem.Application.csproj" />
    <ProjectReference Include="..\BookingSystem.Core\BookingSystem.Core.csproj" />
  </ItemGroup>

</Project>
